spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    open-in-view: false

app:
  jwt-secret: ${SECRET_KEY}
  jwt-expiration-milliseconds: 3600000